### ISSUE TITLE
Basic filtering

### ISSUE THREAD

**Issue by mfenner** [datacite/sashimi#11]
Research what filtering can be done directly in `sashimi`, considering that we send usage stats to Event Data.

Implement basic filtering.

**Comment by kjgarza** [comment]
Current filtering includes:

**Comment by kjgarza** [comment]
We can Filter by 
created_by: https://metrics.test.datacite.org/reports?created-by=dash
year: https://metrics.datacite.org/reports?year=2018
client_id: https://metrics.datacite.org/reports?client-id=dash

I think we can close it @mfenner

**Comment by mfenner** [comment]
I thought we use `api.datacite.org`?

**Comment by kjgarza** [comment]
We didn't move it last week because scott was still  making changes with reports. And I need to update All the events in EventData with the change of report_id. The report ID its in the subj-id in the each of the events, which means all events need to be updated. But this is a different issue datacite/mastino#22 not about this.
